version: '1.0'

services:
    spike-api:
        image: spike-api
        ports:
            - "8000:8000"
        volumes:
            - ./model:/model
    spike-pipeline:
        image: spike-pipeline
        volumes:
            - ./model:/model
            - ./pipeline/logs:/app/logs
            - ./pipeline/tmp:/app/tmpwandb
            - ./pipeline/models:/app/models
    